# Configuration for chart-testing
# See https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md

target-branch: main
chart-dirs:
  - .
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: false
validate-maintainers: false
