apiVersion: v2
name: n8n
description: A Helm chart for n8n workflow automation platform with PostgreSQL and Redis
type: application
version: 1.95.3-4
appVersion: "1.95.3"
icon: https://n8n.io/favicon.ico
keywords:
  - n8n
  - workflow
  - automation
  - postgresql
  - redis
home: https://n8n.io/
sources:
  - https://github.com/n8n-io/n8n
maintainers:
  - name: wearewebera
dependencies:
  - name: postgresql
    version: "15.5.36"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "20.3.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
