apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: N8N_ENCRYPTION_KEY
              {{- if .Values.n8n.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.n8n.existingSecret }}
                  key: {{ .Values.n8n.existingSecretKey | default "encryption-key" }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-secret
                  key: encryption-key
              {{- end }}
            - name: EXECUTIONS_MODE
              value: {{ .Values.n8n.executions_mode | quote }}
            {{- if and .Values.redis.enabled (eq .Values.n8n.queue_mode "redis") }}
            - name: QUEUE_BULL_REDIS_HOST
              value: {{ include "n8n.fullname" . }}-redis-master
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-redis
                  key: redis-password
            {{- end }}
            - name: N8N_PORT
              value: "5678"
            {{- if .Values.postgresql.enabled }}
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              value: {{ include "n8n.fullname" . }}-postgresql
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: DB_POSTGRESDB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}-postgresql
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.n8n.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.n8n.persistence.enabled }}
            - name: n8n-data
              mountPath: /home/node/.n8n
            {{- end }}
            # Temporary filesystems for read-only root filesystem
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /home/node/.cache
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.n8n.persistence.enabled }}
        - name: n8n-data
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}-data
        {{- end }}
        # Temporary filesystems for security
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}