name: Release Helm Chart

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to release'
        required: true
        default: '0.1.0'

env:
  REGISTRY: ghcr.io
  CHART_NAME: n8n

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'
          
      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
          
      - name: Update dependencies
        run: |
          helm dependency update
          
      - name: Package chart
        run: |
          helm package .
          
      - name: Push chart to registry
        run: |
          CHART_VERSION=$(helm show chart . | grep '^version:' | awk '{print $2}')
          CHART_FILE="${{ env.CHART_NAME }}-${CHART_VERSION}.tgz"
          helm push "${CHART_FILE}" oci://${{ env.REGISTRY }}/${{ github.repository_owner }}
          
      - name: Upload chart to release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: "*.tgz"
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}