name: Helm Chart Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and Test Helm Chart

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Lint Helm Chart
        run: |
          helm lint .

      - name: Run Helm Unit Tests
        run: |
          helm unittest --color  .
